version: "3.8"

services:
  # Pinpoint HBase
  pinpoint-hbase:
    image: pinpointdocker/pinpoint-hbase:2.5.3
    container_name: pinpoint-hbase
    networks:
      - pinpoint-network
    environment:
      - HBASE_HEAPSIZE=512m
    volumes:
      - pinpoint-hbase-data:/home/pinpoint/hbase
    ports:
      - "2181:2181"
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
    restart: unless-stopped

  # Pinpoint Collector
  pinpoint-collector:
    image: pinpointdocker/pinpoint-collector:2.5.3
    container_name: pinpoint-collector
    networks:
      - pinpoint-network
    depends_on:
      - pinpoint-hbase
    environment:
      - HBASE_HOST=pinpoint-hbase
      - HBASE_PORT=2181
      - PINPOINT_ZOOKEEPER_ADDRESS=pinpoint-hbase:2181
      - CLUSTER_ENABLE=false
      - LOGGING_LEVEL_ROOT=INFO
      - FLINK_CLUSTER_ENABLE=false
    ports:
      - "9991:9991"  # UDP Stat
      - "9992:9992"  # UDP Span  
      - "9993:9993"  # TCP
      - "9994:9994"  # TCP Stat
      - "9995:9995"  # TCP Span
      - "9996:9996"  # TCP Meta
    restart: unless-stopped

  # Pinpoint Web UI
  pinpoint-web:
    image: pinpointdocker/pinpoint-web:2.5.3
    container_name: pinpoint-web
    networks:
      - pinpoint-network
    depends_on:
      - pinpoint-hbase
      - pinpoint-collector
    environment:
      - HBASE_HOST=pinpoint-hbase
      - HBASE_PORT=2181
      - PINPOINT_ZOOKEEPER_ADDRESS=pinpoint-hbase:2181
      - CLUSTER_ENABLE=false
      - ADMIN_PASSWORD=admin123
      - CONFIG_SENDUSAGE=false
      - LOGGING_LEVEL_ROOT=INFO
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Pinpoint Batch (선택사항 - 알람 및 배치 작업용)
  pinpoint-batch:
    image: pinpointdocker/pinpoint-batch:2.5.3
    container_name: pinpoint-batch
    networks:
      - pinpoint-network
    depends_on:
      - pinpoint-hbase
    environment:
      - HBASE_HOST=pinpoint-hbase
      - HBASE_PORT=2181
      - PINPOINT_ZOOKEEPER_ADDRESS=pinpoint-hbase:2181
      - BATCH_ENABLE=true
      - BATCH_SERVER_IP=pinpoint-batch
      - LOGGING_LEVEL_ROOT=INFO
    restart: unless-stopped

networks:
  pinpoint-network:
    driver: bridge

volumes:
  pinpoint-hbase-data:
    driver: local