# docker-compose.yml

services:
  hbase:
    image: "pinpointdocker/pinpoint-hbase:3.0.3"
    platform: linux/amd64  # <-- 이 줄을 추가해주세요!
    container_name: "pinpoint-hbase"
    ports:
      - "2181:2181"
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    networks:
      - pinpoint-network

  collector:
    image: "pinpointdocker/pinpoint-collector:3.0.3"
    platform: linux/amd64  # <-- 이 줄을 추가해주세요!
    container_name: "pinpoint-collector"
    depends_on:
      - hbase
    ports:
      - "9991:9991"
      - "9992:9992"
      - "9993:9993"
    networks:
      - pinpoint-network

  web:
    image: "pinpointdocker/pinpoint-web:3.0.3"
    platform: linux/amd64  # <-- 이 줄을 추가해주세요!
    container_name: "pinpoint-web"
    depends_on:
      - hbase
      - collector
    ports:
      - "8080:8080"
    networks:
      - pinpoint-network

networks:
  pinpoint-network:
    driver: bridge