# docker-compose.yml
version: '3.3'
services:
  # HBase (Zookeeper 포함)
  hbase:
    image: pinpointdocker/pinpoint-hbase:2.5.3
    container_name: pinpoint-hbase
    ports:
      - "2181:2181" # Zookeeper
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
      - "16010:16010" # HBase Master UI
    networks:
      - pinpoint_network

  # Pinpoint Collector
  collector:
    image: pinpointdocker/pinpoint-collector:2.5.3
    container_name: pinpoint-collector
    ports:
      - "9991:9991"
      - "9992:9992"
      - "9993:9993"
    depends_on:
      - hbase
    networks:
      - pinpoint_network
    environment:
      - "HBASE_HOST=hbase"

  # Pinpoint Web UI
  web:
    image: pinpointdocker/pinpoint-web:2.5.3
    container_name: pinpoint-web
    ports:
      - "8080:8080" # Pinpoint Web UI 포트
    depends_on:
      - hbase
    networks:
      - pinpoint_network
    environment:
      - "HBASE_HOST=hbase"

networks:
  pinpoint_network:
    driver: bridge